/**
 * Agency Pulse API v1.0
 * API für das Agency Pulse - Einsatzplanungssystem
 *
 * OpenAPI spec version: 1.0
 * Contact: development@de.cpm-int.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListResponse } from './listResponse';

export interface AttributeResponse { 
    id?: string;
    displayTypeId?: number;
    list?: ListResponse;
    name?: string;
    label?: string;
    forEntitiyId?: number;
    mandatory?: boolean;
    position?: number;
    positionGroupId?: string;
}