export * from './appointmentQuestionnaireResults.service';
import { AppointmentQuestionnaireResultsService } from './appointmentQuestionnaireResults.service';
export * from './appointments.service';
import { AppointmentsService } from './appointments.service';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './dataLocked.service';
import { DataLockedService } from './dataLocked.service';
export * from './displayTypes.service';
import { DisplayTypesService } from './displayTypes.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './organisationalUnits.service';
import { OrganisationalUnitsService } from './organisationalUnits.service';
export * from './positionGroups.service';
import { PositionGroupsService } from './positionGroups.service';
export * from './projectTemplates.service';
import { ProjectTemplatesService } from './projectTemplates.service';
export * from './projects.service';
import { ProjectsService } from './projects.service';
export * from './reportLinkTypes.service';
import { ReportLinkTypesService } from './reportLinkTypes.service';
export * from './settings.service';
import { SettingsService } from './settings.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export const APIS = [AppointmentQuestionnaireResultsService, AppointmentsService, AuthenticationService, ClientsService, DataLockedService, DisplayTypesService, LocationService, OrganisationalUnitsService, PositionGroupsService, ProjectTemplatesService, ProjectsService, ReportLinkTypesService, SettingsService, StatusService, WeatherForecastService];
