/**
 * Agency Pulse API v1.0
 * API für das Agency Pulse - Einsatzplanungssystem
 *
 * OpenAPI spec version: 1.0
 * Contact: development@de.cpm-int.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AppointmentQuestionnaireResultResponse } from '../model/appointmentQuestionnaireResultResponse';
import { ProblemDetails } from '../model/problemDetails';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AppointmentQuestionnaireResultsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Returns a list of AppointmentQuestionnaireResults. You can apply filters using the query parameters
     * Returns a list of AppointmentQuestionnaireResults. You can apply filters using the query parameters
     * @param projectIds A comma separated list of project ids. This parameter is mandatory.
     * @param expand Returns also related entities if set to &#x27;true&#x27;
     * @param categoryIds A comma separated list of category ids
     * @param questionnaireIds A comma separated list of questionnaire ids
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public appointmentQuestionnaireResultsGet(projectIds: string, expand?: boolean, categoryIds?: string, questionnaireIds?: string, observe?: 'body', reportProgress?: boolean): Observable<Array<AppointmentQuestionnaireResultResponse>>;
    public appointmentQuestionnaireResultsGet(projectIds: string, expand?: boolean, categoryIds?: string, questionnaireIds?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AppointmentQuestionnaireResultResponse>>>;
    public appointmentQuestionnaireResultsGet(projectIds: string, expand?: boolean, categoryIds?: string, questionnaireIds?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AppointmentQuestionnaireResultResponse>>>;
    public appointmentQuestionnaireResultsGet(projectIds: string, expand?: boolean, categoryIds?: string, questionnaireIds?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (projectIds === null || projectIds === undefined) {
            throw new Error('Required parameter projectIds was null or undefined when calling appointmentQuestionnaireResultsGet.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (expand !== undefined && expand !== null) {
            queryParameters = queryParameters.set('expand', <any>expand);
        }
        if (projectIds !== undefined && projectIds !== null) {
            queryParameters = queryParameters.set('projectIds', <any>projectIds);
        }
        if (categoryIds !== undefined && categoryIds !== null) {
            queryParameters = queryParameters.set('categoryIds', <any>categoryIds);
        }
        if (questionnaireIds !== undefined && questionnaireIds !== null) {
            queryParameters = queryParameters.set('questionnaireIds', <any>questionnaireIds);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<AppointmentQuestionnaireResultResponse>>('get',`${this.basePath}/AppointmentQuestionnaireResults`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
