/**
 * Agency Pulse API v1.0
 * API für das Agency Pulse - Einsatzplanungssystem
 *
 * OpenAPI spec version: 1.0
 * Contact: development@de.cpm-int.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AttributeCreationRequest } from '../model/attributeCreationRequest';
import { AttributeEditRequest } from '../model/attributeEditRequest';
import { AttributeResponse } from '../model/attributeResponse';
import { ClientCreationRequest } from '../model/clientCreationRequest';
import { ClientEditRequest } from '../model/clientEditRequest';
import { ClientResponse } from '../model/clientResponse';
import { ProblemDetails } from '../model/problemDetails';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ClientsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Deletes a attribute with the given attributeId
     * Deletes a attribute with the given attribute
     * @param clientId The clientId from the client with contains the attribute
     * @param attributeId The attributeId from the attribute to be deleted
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsClientIdAppointmentAttributesAttributeIdDelete(clientId: string, attributeId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public clientsClientIdAppointmentAttributesAttributeIdDelete(clientId: string, attributeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public clientsClientIdAppointmentAttributesAttributeIdDelete(clientId: string, attributeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public clientsClientIdAppointmentAttributesAttributeIdDelete(clientId: string, attributeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientId === null || clientId === undefined) {
            throw new Error('Required parameter clientId was null or undefined when calling clientsClientIdAppointmentAttributesAttributeIdDelete.');
        }

        if (attributeId === null || attributeId === undefined) {
            throw new Error('Required parameter attributeId was null or undefined when calling clientsClientIdAppointmentAttributesAttributeIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/Clients/${encodeURIComponent(String(clientId))}/appointmentAttributes/${encodeURIComponent(String(attributeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a single attribute within a client
     * Returns a single attribute within a client
     * @param clientId 
     * @param attributeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsClientIdAppointmentAttributesAttributeIdGet(clientId: string, attributeId: string, observe?: 'body', reportProgress?: boolean): Observable<AttributeResponse>;
    public clientsClientIdAppointmentAttributesAttributeIdGet(clientId: string, attributeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AttributeResponse>>;
    public clientsClientIdAppointmentAttributesAttributeIdGet(clientId: string, attributeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AttributeResponse>>;
    public clientsClientIdAppointmentAttributesAttributeIdGet(clientId: string, attributeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientId === null || clientId === undefined) {
            throw new Error('Required parameter clientId was null or undefined when calling clientsClientIdAppointmentAttributesAttributeIdGet.');
        }

        if (attributeId === null || attributeId === undefined) {
            throw new Error('Required parameter attributeId was null or undefined when calling clientsClientIdAppointmentAttributesAttributeIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AttributeResponse>('get',`${this.basePath}/Clients/${encodeURIComponent(String(clientId))}/appointmentAttributes/${encodeURIComponent(String(attributeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates a attribute within a client
     * Updates a attribute within a client
     * @param clientId The clientId from the client with contains the attribute
     * @param attributeId The attributeId from the attribute to be updated
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsClientIdAppointmentAttributesAttributeIdPut(clientId: string, attributeId: string, body?: AttributeEditRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public clientsClientIdAppointmentAttributesAttributeIdPut(clientId: string, attributeId: string, body?: AttributeEditRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public clientsClientIdAppointmentAttributesAttributeIdPut(clientId: string, attributeId: string, body?: AttributeEditRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public clientsClientIdAppointmentAttributesAttributeIdPut(clientId: string, attributeId: string, body?: AttributeEditRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientId === null || clientId === undefined) {
            throw new Error('Required parameter clientId was null or undefined when calling clientsClientIdAppointmentAttributesAttributeIdPut.');
        }

        if (attributeId === null || attributeId === undefined) {
            throw new Error('Required parameter attributeId was null or undefined when calling clientsClientIdAppointmentAttributesAttributeIdPut.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/Clients/${encodeURIComponent(String(clientId))}/appointmentAttributes/${encodeURIComponent(String(attributeId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a list of attributes within a client
     * Returns a list of attributes within a client
     * @param clientId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsClientIdAppointmentAttributesGet(clientId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<AttributeResponse>>;
    public clientsClientIdAppointmentAttributesGet(clientId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<AttributeResponse>>>;
    public clientsClientIdAppointmentAttributesGet(clientId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<AttributeResponse>>>;
    public clientsClientIdAppointmentAttributesGet(clientId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientId === null || clientId === undefined) {
            throw new Error('Required parameter clientId was null or undefined when calling clientsClientIdAppointmentAttributesGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<AttributeResponse>>('get',`${this.basePath}/Clients/${encodeURIComponent(String(clientId))}/appointmentAttributes`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Creates a new attribute within a client
     * Creates a new attribute within a client
     * @param clientId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsClientIdAppointmentAttributesPost(clientId: string, body?: AttributeCreationRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public clientsClientIdAppointmentAttributesPost(clientId: string, body?: AttributeCreationRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public clientsClientIdAppointmentAttributesPost(clientId: string, body?: AttributeCreationRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public clientsClientIdAppointmentAttributesPost(clientId: string, body?: AttributeCreationRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientId === null || clientId === undefined) {
            throw new Error('Required parameter clientId was null or undefined when calling clientsClientIdAppointmentAttributesPost.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/Clients/${encodeURIComponent(String(clientId))}/appointmentAttributes`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Deletes a client
     * Deletes a client
     * @param clientId Deletes a client from the Database.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsClientIdDelete(clientId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public clientsClientIdDelete(clientId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public clientsClientIdDelete(clientId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public clientsClientIdDelete(clientId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientId === null || clientId === undefined) {
            throw new Error('Required parameter clientId was null or undefined when calling clientsClientIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/Clients/${encodeURIComponent(String(clientId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a single client.
     * Returns a single Client in database.
     * @param clientId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsClientIdGet(clientId: string, observe?: 'body', reportProgress?: boolean): Observable<ClientResponse>;
    public clientsClientIdGet(clientId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ClientResponse>>;
    public clientsClientIdGet(clientId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ClientResponse>>;
    public clientsClientIdGet(clientId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientId === null || clientId === undefined) {
            throw new Error('Required parameter clientId was null or undefined when calling clientsClientIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ClientResponse>('get',`${this.basePath}/Clients/${encodeURIComponent(String(clientId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Updates a client
     * Updates a client
     * @param clientId The clientId from the client
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsClientIdPut(clientId: string, body?: ClientEditRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public clientsClientIdPut(clientId: string, body?: ClientEditRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public clientsClientIdPut(clientId: string, body?: ClientEditRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public clientsClientIdPut(clientId: string, body?: ClientEditRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (clientId === null || clientId === undefined) {
            throw new Error('Required parameter clientId was null or undefined when calling clientsClientIdPut.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/Clients/${encodeURIComponent(String(clientId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Returns a list of Clients. You can apply filters using the query parameters
     * Returns all Clients in database if no filters are applied.
     * @param expand Returns also related entities if set to &#x27;true&#x27;
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsGet(expand?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<ClientResponse>>;
    public clientsGet(expand?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<ClientResponse>>>;
    public clientsGet(expand?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<ClientResponse>>>;
    public clientsGet(expand?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (expand !== undefined && expand !== null) {
            queryParameters = queryParameters.set('expand', <any>expand);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<ClientResponse>>('get',`${this.basePath}/Clients`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Creates a new client
     * Creates a new client
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public clientsPost(body?: ClientCreationRequest, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public clientsPost(body?: ClientCreationRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public clientsPost(body?: ClientCreationRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public clientsPost(body?: ClientCreationRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/Clients`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
