/**
 * Agency Pulse API v1.0
 * API für das Agency Pulse - Einsatzplanungssystem
 *
 * OpenAPI spec version: 1.0
 * Contact: development@de.cpm-int.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { OrganisationalUnitResponse } from '../model/organisationalUnitResponse';
import { ProblemDetails } from '../model/problemDetails';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class OrganisationalUnitsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Returns a list of OrganisationalUnits. You can apply filters using the query parameters
     * Returns all OrganisationalUnits in database if no filters are applied.
     * @param expand Returns also related entities if set to &#x27;true&#x27;
     * @param type 1&#x3D;Client;2&#x3D;Project;3&#x3D;Chain;4&#x3D;Area;5&#x3D;Staff;6&#x3D;Locations;7&#x3D;Hierarchy;8&#x3D;Category;9&#x3D;Task              10&#x3D;AppointmentGroup;11&#x3D;AppointmentTeam;12&#x3D;ArticleGroup
     * @param validFrom The date from which the OrganisationalUnit can be used
     * @param validTo The date until when the OrganisationalUnit can be used
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public organisationalUnitsGet(expand?: boolean, type?: number, validFrom?: Date, validTo?: Date, observe?: 'body', reportProgress?: boolean): Observable<Array<OrganisationalUnitResponse>>;
    public organisationalUnitsGet(expand?: boolean, type?: number, validFrom?: Date, validTo?: Date, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<OrganisationalUnitResponse>>>;
    public organisationalUnitsGet(expand?: boolean, type?: number, validFrom?: Date, validTo?: Date, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<OrganisationalUnitResponse>>>;
    public organisationalUnitsGet(expand?: boolean, type?: number, validFrom?: Date, validTo?: Date, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (expand !== undefined && expand !== null) {
            queryParameters = queryParameters.set('expand', <any>expand);
        }
        if (type !== undefined && type !== null) {
            queryParameters = queryParameters.set('type', <any>type);
        }
        if (validFrom !== undefined && validFrom !== null) {
            queryParameters = queryParameters.set('validFrom', <any>validFrom.toISOString());
        }
        if (validTo !== undefined && validTo !== null) {
            queryParameters = queryParameters.set('validTo', <any>validTo.toISOString());
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<OrganisationalUnitResponse>>('get',`${this.basePath}/OrganisationalUnits`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
